spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

server:
  port: 8000
